---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helifight
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - helifight.samarchyan.me
      secretName: helifight-tls
  rules:
    - host: helifight.samarchyan.me
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: helifight
                port:
                  number: 3000
